---
  - name: Add an Apt signing key for redis repo
    ansible.builtin.apt_key:
      url: https://packages.redis.io/gpg
      state: present

  - name: Add redis repository into sources list
    ansible.builtin.apt_repository:
      repo: deb https://packages.redis.io/deb {{ ansible_distribution_release }} main
      state: present
    register: redis_apt_repo

  - name: Purge distro redis package
    apt:
      name: redis-server
      state: absent
      purge: true
    when: redis_apt_repo.changed

  - name: Install Redis from official repo
    become: true
    apt:
      name: redis-server
      state: latest
      update_cache: true

  - name: Set bind IP
    become: true
    lineinfile:
      name: /etc/redis/redis.conf
      regexp: '^bind '
      line: 'bind {{redis_bind}}'
      state: present

  - name: Disable protected-mode
    become: true
    lineinfile:
      name: /etc/redis/redis.conf
      regexp: '^protected-mode yes'
      line: 'protected-mode no'

  - name: enable redis
    become: true
    systemd:
      name: redis-server
      enabled: yes

  - name: restart redis
    become: true
    systemd:
      name: redis-server
      state: restarted
