---
  - name: Remove old redis repo if present (Pre subspace 3.1)
    ansible.builtin.file:
      path: /etc/apt/sources.list.d/packages_redis_io_deb.list
      state: absent

  - name: Add official redis repo
    ansible.builtin.deb822_repository:
      name: redis
      types: [deb]
      uris: "https://packages.redis.io/deb"
      components: [main]
      suites: [ "{{ ansible_facts['distribution_release'] }}" ]
      signed_by: https://packages.redis.io/gpg

  - name: Install Redis from official repo
    become: true
    apt:
      name: redis-server
      state: latest
      update_cache: true

  - name: Set bind IP
    become: true
    lineinfile:
      name: /etc/redis/redis.conf
      regexp: '^bind '
      line: 'bind {{redis_bind}}'
      state: present

  - name: Disable protected-mode
    become: true
    lineinfile:
      name: /etc/redis/redis.conf
      regexp: '^protected-mode yes'
      line: 'protected-mode no'

  - name: enable redis
    become: true
    systemd:
      name: redis-server
      enabled: yes

  - name: restart redis
    become: true
    systemd:
      name: redis-server
      state: restarted
