---
  - name: Add an Apt signing key for redis repo
    ansible.builtin.apt_key:
      url: https://packages.redis.io/gpg
      state: present

  - name: Add redis repository into sources list
    ansible.builtin.apt_repository:
      repo: deb https://packages.redis.io/deb {{ ansible_distribution_release }} main
      state: present

  - name: Install Redis
    become: true
    apt:
      name: redis-server
      state: latest
      update_cache: true

  - name: Set bind IP
    become: true
    lineinfile:
      name: /etc/redis/redis.conf
      regexp: '^bind '
      line: 'bind {{redis_bind}}'
      state: present

  - name: restart redis
    become: true
    systemd:
      name: redis
      state: restarted
