---
  - name: Install Redis
    become: true
    apt:
      pkg: redis-server
      state: present
      update_cache: true

  - name: Set bind IP
    become: true
    lineinfile:
      name: /etc/redis/redis.conf
      regexp: '^bind '
      line: 'bind {{redis_bind}}'
      state: present

  - name: restart redis
    become: true
    systemd:
      name: redis
      state: restarted
