---
  certbot_dir: "/opt/certbot"
  le_ssl_cert:
    cert_name: "{{server_name}}"
    preferred_challenges: "http"
    plugin: standalone
    domains: "{{ [server_name] + server_aliases }}"

  nginx_ssl_config: |
    ssl_certificate /etc/letsencrypt/live/{{le_ssl_cert.cert_name}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{le_ssl_cert.cert_name}}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
