---
  - name: Install ca-certificates
    become: true
    apt:
      pkg: "{{item}}"
      state: present
    with_items:
      - ca-certificates
    
  - name: Install certbot-nginx
    become: true
    when: "'nginx' in role_names"
    apt:
      pkg: python3-certbot-nginx
      state: present

  - name: "Set certbot binary"
    set_fact:
      certbot_bin: "certbot"

  - name: "Check for certbot-auto"
    stat:
      path: /opt/certbot/certbot-auto
    register: certbot_auto_exists

  - name: "Remove certbot-auto"
    file:
      path: /opt/certbot/certbot-auto
      state: absent
    when: certbot_auto_exists.stat.exists

  - name: "Remove certbot-auto cron task"
    cron:
      name: Auto-renew SSL
      job: "{{certbot_bin}} renew --no-self-upgrade --nginx >> /var/log/cron.log 2>&1"
      hour: "0"
      minute: "33"
      state: absent
    when: certbot_auto_exists.stat.exists
