---
  - name: Install systemd sidekiq script
    become: true
    template:
      src: sidekiq-systemd.service
      dest: /etc/systemd/system/sidekiq.service

  - name: Enable systemd sidekiq service
    become: true
    systemd:
      name: sidekiq
      enabled: yes
      daemon_reload: true

# TODO Read the gemfile and make sure they have sidekiq 6????
