---
- name: turn off swap
  become: true
  command: swapoff -a

- name: set swapiness
  become: true
  sysctl:
    name: vm.swappiness
    value: "0"

- name: delete swap file
  become: true
  file:
    path: /swapfile
    state: absent

- name: remove from fstab
  become: true
  lineinfile:
    dest: /etc/fstab
    regexp: /swapfile
    line: "/swapfile none swap sw 0 0"
    state: absent


