#!/bin/bash

echo CERTBOT_VALIDATION=$CERTBOT_VALIDATION
echo CERTBOT_DOMAIN=$CERTBOT_DOMAIN
echo CERTBOT_TOKEN=$CERTBOT_TOKEN
echo CERTBOT_ALL_DOMAINS=$CERTBOT_ALL_DOMAINS


echo "for dns you need to set:"
echo "IN TXT  _acme_challenge.$CERTBOT_DOMAIN \"$CERTBOT_VALIDATION\""

