---
- name: Add Yarn official APT repository
  ansible.builtin.deb822_repository:
    name: yarn
    types: [deb]
    uris: "http://dl.yarnpkg.com/debian/"
    components: [main]
    suites: [stable]
    signed_by: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
    enabled: true

- name: "Install yarn from official repo"
  become: yes
  become_user: root
  apt:
    pkg: yarn
    state: latest
    update_cache: yes
