---
- name: stop webserver
  service: name=nginx state=stopped
  become: true

- name: start webserver
  service: name=nginx state=started
  become: true

- name: restart webserver
  service: name=nginx state=restarted
  become: true
