class Subspace::Commands::Inventory < Subspace::Commands::Base

  def self.server_lines(inventory, group)
    inventory.find_hosts!(group).map do |host|
      host = inventory.hosts[host.name]
      roles = host.group_list.map do |group_name|
        if group_name =~ /web/
          ["web", "app"]
        elsif group_name =~ /worker/
          ["app", "db"]
        end
      end.compact.uniq
      "server '#{host.vars["ansible_host"]}', user: 'deploy', roles: %w{#{roles.join(' ')}} # #{host.vars["hostname"]}"
    end
  end

  def self.write_capistrano_stage(inventory, group:, rails_env:, path:)
    FileUtils.mkdir_p File.dirname(path)
    File.write path, ([
      "# #{path}",
      "# Generated by Subspace",
      "set :rails_env, '#{rails_env}'",
    ] + server_lines(inventory, group)).join("\n") + "\n"
  end

  def initialize(args, options)
    command = args.first
    @env = options.env
    @options = options
    case command
    when "capistrano"
      capistrano_deployrb
    when "list"
      list_inventory
    when "keyscan"
      keyscan_inventory
    else
      say "Unknown or missing command to inventory: #{command}"
      say "try subspace inventory [list, capistrano]"
    end
  end

  def list_inventory
    inventory.find_hosts!(@env || "all").each do |host|
      puts "#{host.name}\t#{host.vars["ansible_host"]}\t(#{host.group_list.join ','})"
    end
  end

  def keyscan_inventory
    inventory.find_hosts!(@env || "all").each do |host|
      ip = host.vars["ansible_host"]
      system %Q(ssh-keygen -R #{ip})
      system %Q(ssh-keyscan -Ht ed25519 #{ip} >> "$HOME/.ssh/known_hosts")
    end
  end

  def capistrano_deployrb
    if @env.nil?
      puts "Please provide an environment e.g: subspace inventory capistrano --env production"
      exit
    end

    rails_env = @options.rails_env || @env
    if @options.output
      self.class.write_capistrano_stage inventory, group: @env, rails_env: rails_env, path: @options.output
      say "Wrote #{@options.output}"
    else
      say "# config/deploy/#{@env}.rb"
      say "# Generated by Subspace"
      say "set :rails_env, '#{rails_env}'"
      self.class.server_lines(inventory, @env).each { |line| say line }
    end
  end
end
