class Subspace::Commands::Inventory < Subspace::Commands::Base

  def initialize(args, options)
    command = args.first
    @env = options.env
    case command
    when "capistrano"
      capistrano_deployrb
    else
      say "Unknown or missing command to inventory: #{command}"
    end

  end

  def capistrano_deployrb
    inventory.find_hosts!(@env).each do |host|
      db_role = false
      roles = host.group_list.map do |group_name|
        if group_name =~ /web/
          ["web", "app"]
        elsif group_name =~ /worker/
          ["app", db_role ? nil : "db"]
        end
      end.compact.uniq

      say "# config/deploy/#{@env}.rb"
      say "# Generated by Subspace"
      say "server '#{host.vars["ansible_host"]}', user: 'deploy', roles: %w{#{roles.join(' ')}} # #{host.vars["hostname"]}"
    end
  end
end
