---
- name: create nginx config for rails app
  template:
    src: nginx-project
    dest: /etc/nginx/sites-available/{{project_name}}
  become: true

- name: Enable the app
  file:
    src: /etc/nginx/sites-available/{{project_name}}
    dest: /etc/nginx/sites-enabled/{{project_name}}
    state: link
  when: ssl_enabled != true or nginx_ssl_config is not defined
  become: true

- name: Disable the app
  file:
    dest: /etc/nginx/sites-enabled/{{project_name}}
    state: absent
  when: (ssl_enabled and nginx_ssl_config is defined)
  become: true

- name: create ssl nginx config for rails app
  template:
    src: nginx-project-ssl
    dest: /etc/nginx/sites-available/{{project_name}}-ssl
  when: (ssl_enabled and nginx_ssl_config is defined)
  become: true

- name: Enable SSL configured app
  file:
    src: /etc/nginx/sites-available/{{project_name}}-ssl
    dest: /etc/nginx/sites-enabled/{{project_name}}-ssl
    state: link
  when: (ssl_enabled and nginx_ssl_config is defined)
  become: true

- name: Disable SSL configured app
  file:
    dest: /etc/nginx/sites-enabled/{{project_name}}-ssl
    state: absent
  when: ssl_enabled != true or nginx_ssl_config is not defined
  become: true

- name: Enable a default server if one is not defined in the app
  template:
    src: 'default_server'
    dest: /etc/nginx/sites-enabled/default_server
    mode: 0644
    group: root
    owner: root
  become: true
  when: not default_server

