---
- hosts: localhost
  remote_user: root
  vars_files:
    - 'vars/main.yml'
    - 'defaults/main.yml'
  tasks:
    - import_tasks: 'tasks/main.yml'
  handlers:
    - import_tasks: 'handlers/main.yml'
