---
- name: Add PostgreSQL official APT repository
  ansible.builtin.deb822_repository:
    name: postgresql
    types: [deb]
    uris: "http://apt.postgresql.org/pub/repos/apt/"
    suites: [ "{{ ansible_facts['distribution_release'] }}-pgdg" ]
    components: [main]
    signed_by: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
    enabled: true
  register: pg_apt

- name: Update package cache if PG repo was added
  become: yes
  when: pg_apt.changed
  apt:
    update_cache: yes

- name: Install PostgreSQL Client
  become: yes
  apt:
    name: "postgresql-client-{{postgresql_version}}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - postgresql
    - db
    - deps

- name: Install libpq-dev
  become: yes
  apt:
    name: "libpq-dev"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - postgresql
    - db
    - deps

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - postgresql
    - db
    - deps

- name: Install psycopg2
  become: yes
  pip:
    name: psycopg2
    break_system_packages: true
  tags:
    - postgresql
    - db
    - deps

- name: Grab PostgreSQL database version
  shell: psql -h "{{database_host}}" -U "{{database_user}}" -d "{{database_name}}" -t -c "SELECT version();" | awk '{print $2}'
  register: stats_psql_version
  environment:
    PGPASSWORD: "{{database_password}}"
  when: send_stats == true and stats_url is defined and stats_api_key is defined
  tags:
    - maintenance
    - stats

- name: Send Psql stats to URL
  uri:
    url: "{{stats_url}}"
    method: POST
    headers:
      X-API-Version: 1
      X-Client-Api-key: "{{stats_api_key}}"
    body_format: json
    body:
      client_stat:
        stat_type: psql_version
        value: "{{stats_psql_version.stdout}}"
        hostname: "{{hostname}}"
  when: send_stats == true and stats_url is defined and stats_api_key is defined
  tags:
    - maintenance
    - stats
