# Variables: papertrail_host, papertrail_port
files:
  - /u/apps/{{project_name}}/shared/log/{{rails_env}}.log
{% if nginx_installed is defined %}
  - /var/log/nginx/error.log
{% endif %}
{% if apache_installed is defined %}
  - /var/log/apache2/error.log
{% endif %}

destination:
  host: {{papertrail_host}}
  port: {{papertrail_port}}
  protocol: tls
