---
  - name: "Add Tailscale apt key"
    become: true
    apt_key:
      url: https://pkgs.tailscale.com/stable/ubuntu/{{ansible_distribution_release}}.gpg
      state: present
    tags:
      - maintenance
      - tailscale_reauth

  - name: "Add Tailscale apt repos"
    become: true
    apt_repository:
      repo: "deb https://pkgs.tailscale.com/stable/ubuntu {{ansible_distribution_release}} main"
      state: present
    tags:
      - maintenance
      - tailscale_reauth

  - name: "Allow tailscale to be installed"
    ignore_errors: yes
    dpkg_selections:
      name: tailscale
      selection: install
    tags:
      - maintenance
      - tailscale_reauth

  - name: "Install tailscale from apt"
    apt:
      name: tailscale
      state: present
      allow_downgrade: true
      update_cache: yes
    tags:
      - maintenance
      - tailscale_reauth

  - name: "Join the tailnet and force reauth"
    become: true
    command: tailscale up --ssh --auth-key={{tailscale_auth_key}} --hostname={{project_name | regex_replace('_', '')}}-{{hostname}} --accept-risk=lose-ssh {{tailscale_options}} --force-reauth
    tags: [ 'never', 'tailscale_reauth' ]
