---
  - name: "Add Tailscale apt key"
    become: true
    apt_key:
      url: https://pkgs.tailscale.com/stable/ubuntu/{{ansible_distribution_release}}.gpg
      state: present
    tags:
      - maintenance
      - tailscale_reauth

  - name: "Add Tailscale apt repos"
    become: true
    apt_repository:
      repo: "deb https://pkgs.tailscale.com/stable/ubuntu {{ansible_distribution_release}} main"
      state: present
    tags:
      - maintenance
      - tailscale_reauth

  - name: "Un-pin tailscale version"
    dpkg_selections:
      name: "tailscale"
      selection: install
    when: tailscale_version is undefined
    tags:
      - maintenance
      - tailscale_reauth

  - name: "Install tailscale from apt"
    apt:
      default_release: stable
      name: "tailscale={{tailscale_version}}"
      state: present
      update_cache: yes
      allow_downgrade: true
    tags:
      - maintenance
      - tailscale_reauth

  - name: "Pin tailscale version"
    dpkg_selections:
      name: "tailscale"
      selection: hold
    when: tailscale_version is defined
    tags:
      - maintenance
      - tailscale_reauth

  - name: "Join the tailnet and force reauth"
    become: true
    command: tailscale up --ssh --auth-key={{tailscale_auth_key}} --hostname={{project_name | regex_replace('_', '')}}-{{hostname}} --accept-risk=lose-ssh {{tailscale_options}} --force-reauth
    tags: [ 'never', 'tailscale_reauth' ]
