---
  - name: Remove old redis repo if present (Pre subspace 3.1)
    ansible.builtin.file:
      path: /etc/apt/sources.list.d/pkgs_tailscale_com_stable_ubuntu.list
      state: absent

  - name: Add official tailscale apt repo
    ansible.builtin.deb822_repository:
      name: tailscale
      types: [deb]
      uris: "https://pkgs.tailscale.com/stable/ubuntu"
      components: [main]
      suites: [ "{{ ansible_facts['distribution_release'] }}" ]
      signed_by: https://pkgs.tailscale.com/stable/ubuntu/{{ansible_facts["distribution_release"]}}.gpg


  - name: "Allow tailscale to be installed"
    ignore_errors: yes
    dpkg_selections:
      name: tailscale
      selection: install
    tags:
      - maintenance
      - tailscale_reauth

  - name: "Install tailscale from apt"
    apt:
      name: tailscale
      state: latest
      allow_downgrade: true
      update_cache: yes
      cache_valid_time: 3600
    tags:
      - maintenance
      - tailscale_reauth

  - name: "Join the tailnet and force reauth"
    become: true
    command: tailscale up --ssh --auth-key={{tailscale_auth_key}} --hostname={{project_name | regex_replace('_', '')}}-{{hostname}} --accept-risk=lose-ssh {{tailscale_options}} --force-reauth
    tags: [ 'never', 'tailscale_reauth' ]
