---
  - name: Create collectd configuration dir
    file:
      path: /etc/collectd/collectd.conf.d
      state: directory
      mode: 0755

  #required first so that collectd will start even if the FQDN of the host doesnt' resovle
  - name: Create hostname config
    template:
      src: hostname.conf
      dest: /etc/collectd/collectd.conf.d/hostname.conf
    sudo: true

  - name: Install collectd
    apt:
      pkg: collectd
      state: present
    sudo: true

  - name: Create graphite config
    template:
      src: graphite.conf
      dest: /etc/collectd/collectd.conf.d/graphite.conf
    sudo: true
    notify: restart collectd

  - name: Create df config
    template:
      src: df.conf
      dest: /etc/collectd/collectd.conf.d/df.conf
    sudo: true
    notify: restart collectd

  - name: create delayed_job_postgres config
    template:
      src: delayed_job_postgres.conf
      dest: /etc/collectd/collectd.conf.d/delayed_job_postgres.conf
    sudo: true
    notify: restart collectd
    when: postgresql_installed is defined and delayed_job_installed is defined

  - name: create apache2 config
    template:
      src: apache2.conf
      dest: /etc/collectd/collectd.conf.d/apache2.conf
    sudo: true
    notify: restart collectd
    when: apache2_installed is defined

